# Generated by Django 4.1 on 2022-08-23 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='postid',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
        ),
        migrations.AddField(
            model_name='comment',
            name='userid',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='blog.student'),
        ),
    ]
