# Generated by Django 4.1 on 2022-08-24 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_postid_comment_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='lname',
        ),
    ]
