# Generated by Django 4.1 on 2022-08-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_student_lname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='email',
        ),
    ]
